import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CircleDollarSign, Pencil, Plus, ReceiptText, Trash2 } from "lucide-react";
import { expenseApi } from "../../api/expenseApi";
import Modal from "../../components/common/Modal";

const money = (value: unknown) => `₹${Number(value).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const today = () => new Date().toISOString().slice(0, 10);
const currentMonth = () => { const now = new Date(); return { from: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`, to: today() }; };

export default function Expenses() {
  const client = useQueryClient(); const [editing, setEditing] = useState<any>(null); const [form, setForm] = useState<Record<string, string>>({}); const [filters, setFilters] = useState<Record<string, string>>({}); const [error, setError] = useState("");
  const { data, isLoading } = useQuery({ queryKey: ["expenses", filters], queryFn: () => expenseApi.list(filters) });
  const { data: monthData } = useQuery({ queryKey: ["expenses-month", currentMonth()], queryFn: () => expenseApi.list(currentMonth()) });
  const expenses = data?.data || []; const categories = data?.categories || [];
  const save = useMutation({ mutationFn: () => editing?.id ? expenseApi.update(editing.id, form) : expenseApi.create(form), onSuccess: () => { client.invalidateQueries({ queryKey: ["expenses"] }); client.invalidateQueries({ queryKey: ["expenses-month"] }); setEditing(null); }, onError: (e: any) => setError(e.response?.data?.message || "Could not save expense.") });
  const remove = useMutation({ mutationFn: expenseApi.remove, onSuccess: () => { client.invalidateQueries({ queryKey: ["expenses"] }); client.invalidateQueries({ queryKey: ["expenses-month"] }); } });
  const open = (expense?: any) => { setError(""); setEditing(expense || {}); setForm(expense ? { category: expense.category, amount: String(expense.amount), date: String(expense.date).slice(0, 10), description: expense.description || "" } : { category: "", amount: "", date: today(), description: "" }); };

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Financial control</p><h1 className="mt-1 text-3xl font-extrabold">Expenses</h1><p className="mt-2 text-sm text-slate-500">Track operating costs and spending categories.</p></div><button onClick={() => open()} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white"><Plus className="mr-2 inline h-4 w-4" />Add expense</button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border-l-4 border-red-500 bg-white p-5 shadow-sm"><CircleDollarSign className="h-5 w-5 text-red-500" /><p className="mt-4 text-2xl font-extrabold">{money(data?.summary?.total || 0)}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">Filtered total</p></div><div className="rounded-2xl border-l-4 border-orange-500 bg-white p-5 shadow-sm"><CalendarDays className="h-5 w-5 text-orange-500" /><p className="mt-4 text-2xl font-extrabold">{money(monthData?.summary?.total || 0)}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">This month</p></div><div className="rounded-2xl border-l-4 border-blue-500 bg-white p-5 shadow-sm"><ReceiptText className="h-5 w-5 text-blue-500" /><p className="mt-4 text-2xl font-extrabold">{data?.summary?.count || 0}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">Expense entries</p></div></div>
    <div className="mt-6 grid gap-3 rounded-2xl bg-white p-4 shadow-sm sm:grid-cols-4"><select value={filters.category || ""} onChange={e => setFilters({ ...filters, category: e.target.value })} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">All categories</option>{categories.map((category: string) => <option key={category}>{category}</option>)}</select><input type="date" value={filters.from || ""} onChange={e => setFilters({ ...filters, from: e.target.value })} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><input type="date" value={filters.to || ""} onChange={e => setFilters({ ...filters, to: e.target.value })} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><button onClick={() => setFilters({})} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-bold text-slate-600">Clear filters</button></div>
    <div className="mt-6 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="p-5">Date</th><th className="p-5">Category</th><th className="p-5">Description</th><th className="p-5">Amount</th><th className="p-5 text-right">Actions</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={5} className="p-12 text-center text-slate-400">Loading…</td></tr> : expenses.length === 0 ? <tr><td colSpan={5} className="p-12 text-center text-slate-400">No expenses found.</td></tr> : expenses.map((expense: any) => <tr key={expense.id} className="border-b last:border-0"><td className="p-5 text-slate-500">{new Date(expense.date).toLocaleDateString("en-IN", { timeZone: "UTC" })}</td><td className="p-5"><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700">{expense.category}</span></td><td className="p-5 text-slate-600">{expense.description || "—"}</td><td className="p-5 font-extrabold text-red-600">{money(expense.amount)}</td><td className="p-5"><div className="flex justify-end gap-2"><button onClick={() => open(expense)} className="p-2 text-slate-500"><Pencil className="h-4 w-4" /></button><button onClick={() => confirm("Delete this expense?") && remove.mutate(expense.id)} className="p-2 text-red-500"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div></div>
    {editing && <Modal title={editing.id ? "Edit expense" : "Add expense"} onClose={() => setEditing(null)}><form onSubmit={(e: FormEvent) => { e.preventDefault(); save.mutate(); }} className="grid gap-5 p-6 sm:grid-cols-2">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p>}<label className="text-sm font-semibold">Category<input list="expense-categories" value={form.category || ""} onChange={e => setForm({ ...form, category: e.target.value })} required placeholder="Rent, electricity, supplies" className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /><datalist id="expense-categories">{categories.map((category: string) => <option key={category} value={category} />)}</datalist></label><label className="text-sm font-semibold">Amount<input type="number" min="0.01" step="0.01" value={form.amount || ""} onChange={e => setForm({ ...form, amount: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><label className="text-sm font-semibold sm:col-span-2">Expense date<input type="date" value={form.date || ""} onChange={e => setForm({ ...form, date: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><label className="text-sm font-semibold sm:col-span-2">Description<textarea value={form.description || ""} onChange={e => setForm({ ...form, description: e.target.value })} rows={3} className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={() => setEditing(null)} className="rounded-xl border px-5 py-2.5 text-sm font-bold">Cancel</button><button disabled={save.isPending} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-bold text-white">{save.isPending ? "Saving…" : "Save expense"}</button></div></form></Modal>}
  </div>;
}
