import { useQuery } from "@tanstack/react-query";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, Banknote, Boxes, GraduationCap, TrendingDown, TrendingUp, Users } from "lucide-react";
import { reportApi } from "../../api/reportApi";

const money = (value: unknown) => `₹${Number(value || 0).toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const colors = ["#3B82F6", "#10B981", "#F97316", "#8B5CF6", "#EF4444", "#06B6D4"];
const tooltipMoney = (value: any) => money(Array.isArray(value) ? value[0] : value);

export default function Reports() {
  const { data, isLoading, isError } = useQuery({ queryKey: ["analytics"], queryFn: reportApi.analytics });
  if (isLoading) return <div className="rounded-2xl bg-white p-12 text-center text-slate-400">Loading analytics…</div>;
  if (isError || !data) return <div className="rounded-2xl bg-red-50 p-6 text-red-700">Could not load reports. Make sure the backend is running.</div>;
  const teacher = data.role === "teacher";
  if (teacher) return <div>
    <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Batch insights</p><h1 className="mt-1 text-3xl font-extrabold">Reports & analytics</h1><p className="mt-2 text-sm text-slate-500">Performance statistics for your assigned batches only.</p></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Students", data.summary.students, Users, "border-blue-500"], ["Batches", data.summary.batches, Boxes, "border-violet-500"], ["Attendance", `${data.summary.attendanceRate}%`, TrendingUp, "border-emerald-500"], ["Average score", `${data.summary.averageScore}%`, GraduationCap, "border-orange-500"]].map(([label, value, Icon, border]: any) => <div key={label} className={`rounded-2xl border-l-4 ${border} bg-white p-5 shadow-sm`}><Icon className="h-5 w-5 text-slate-400" /><p className="mt-4 text-3xl font-extrabold">{value}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">{label}</p></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-extrabold">Monthly attendance</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis dataKey="month" /><YAxis domain={[0, 100]} /><Tooltip /><Line type="monotone" dataKey="attendanceRate" name="Attendance %" stroke="#10B981" strokeWidth={3} /></LineChart></ResponsiveContainer></div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-extrabold">My batches</h2><div className="mt-4 divide-y">{data.batches.length === 0 ? <p className="py-10 text-center text-sm text-slate-400">No batches assigned.</p> : data.batches.map((batch: any) => <div key={batch.id} className="flex items-center gap-4 py-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 font-bold text-blue-700">{batch.students}</span><div className="flex-1"><p className="font-bold">{batch.course} · {batch.name}</p><p className="text-xs text-slate-400">{batch.assignments} assignments</p></div><span className="text-xs font-bold text-slate-500">{batch.students} students</span></div>)}</div></section></div>
  </div>;

  const attendanceData = [{ name: "Present", value: data.attendance.present }, { name: "Absent", value: data.attendance.absent }, { name: "Leave", value: data.attendance.leave }];
  return <div>
    <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Business intelligence</p><h1 className="mt-1 text-3xl font-extrabold">Reports & analytics</h1><p className="mt-2 text-sm text-slate-500">Six-month revenue, expenses, attendance, and service performance.</p></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border-l-4 border-emerald-500 bg-white p-5 shadow-sm"><Banknote className="h-5 w-5 text-emerald-500" /><p className="mt-4 text-2xl font-extrabold">{money(data.summary.revenue)}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">Revenue · 6 months</p></div><div className="rounded-2xl border-l-4 border-red-500 bg-white p-5 shadow-sm"><TrendingDown className="h-5 w-5 text-red-500" /><p className="mt-4 text-2xl font-extrabold">{money(data.summary.expenses)}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">Expenses · 6 months</p></div><div className="rounded-2xl border-l-4 border-blue-500 bg-white p-5 shadow-sm"><TrendingUp className="h-5 w-5 text-blue-500" /><p className="mt-4 text-2xl font-extrabold">{money(data.summary.net)}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">Net position</p></div><div className="rounded-2xl border-l-4 border-orange-500 bg-white p-5 shadow-sm"><AlertTriangle className="h-5 w-5 text-orange-500" /><p className="mt-4 text-2xl font-extrabold">{data.summary.lowStock}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">Low-stock items</p></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-3"><section className="rounded-2xl bg-white p-5 shadow-sm xl:col-span-2"><h2 className="font-extrabold">Revenue vs expenses</h2><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthly}><defs><linearGradient id="revenue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#10B981" stopOpacity={0.35} /><stop offset="95%" stopColor="#10B981" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis dataKey="month" /><YAxis tickFormatter={value => `₹${value / 1000}k`} /><Tooltip formatter={tooltipMoney} /><Legend /><Area type="monotone" dataKey="revenue" stroke="#10B981" fill="url(#revenue)" strokeWidth={3} /><Area type="monotone" dataKey="expenses" stroke="#EF4444" fill="transparent" strokeWidth={3} /></AreaChart></ResponsiveContainer></div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-extrabold">Attendance</h2><p className="mt-1 text-sm text-slate-400">Overall rate: {data.summary.attendanceRate}%</p><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={attendanceData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88}>{attendanceData.map((_: any, index: number) => <Cell key={index} fill={colors[index]} />)}</Pie><Tooltip /><Legend /></PieChart></ResponsiveContainer></div></section></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-extrabold">Top cyber services</h2><div className="mt-5 h-72">{data.topServices.length === 0 ? <p className="pt-24 text-center text-sm text-slate-400">No service orders in this period.</p> : <ResponsiveContainer width="100%" height="100%"><BarChart data={data.topServices} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis type="number" /><YAxis type="category" dataKey="name" width={105} /><Tooltip /><Bar dataKey="quantity" name="Units sold" fill="#3B82F6" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer>}</div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-extrabold">Expenses by category</h2><div className="mt-5 h-72">{data.expenseCategories.length === 0 ? <p className="pt-24 text-center text-sm text-slate-400">No expenses in this period.</p> : <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.expenseCategories} dataKey="value" nameKey="name" outerRadius={95}>{data.expenseCategories.map((_: any, index: number) => <Cell key={index} fill={colors[index % colors.length]} />)}</Pie><Tooltip formatter={tooltipMoney} /><Legend /></PieChart></ResponsiveContainer>}</div></section></div>
  </div>;
}
