import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Check, Clock3, Plus, Trash2, X } from "lucide-react";
import { leaveApi } from "../../api/leaveApi";
import Modal from "../../components/common/Modal";
import { useAuth } from "../../context/AuthContext";

const date = (value: string) => new Date(value).toLocaleDateString("en-IN", { timeZone: "UTC" });
const days = (from: string, to: string) => Math.floor((new Date(to).getTime() - new Date(from).getTime()) / 86400000) + 1;
const statusClass: Record<string, string> = { pending: "bg-orange-50 text-orange-700", approved: "bg-emerald-50 text-emerald-700", rejected: "bg-red-50 text-red-700" };

export default function Leave() {
  const { user } = useAuth(); const admin = user?.role === "admin"; const client = useQueryClient();
  const [open, setOpen] = useState(false); const [filter, setFilter] = useState(""); const [form, setForm] = useState({ fromDate: "", toDate: "", reason: "" }); const [error, setError] = useState("");
  const { data, isLoading } = useQuery({ queryKey: ["leave", filter], queryFn: () => leaveApi.list(filter) }); const requests = data?.data || []; const summary = data?.summary || {};
  const refresh = () => client.invalidateQueries({ queryKey: ["leave"] });
  const create = useMutation({ mutationFn: () => leaveApi.create(form), onSuccess: () => { refresh(); setOpen(false); }, onError: (e: any) => setError(e.response?.data?.message || "Could not submit leave request.") });
  const decide = useMutation({ mutationFn: ({ id, status }: { id: number; status: "approved" | "rejected" }) => leaveApi.decide(id, status), onSuccess: refresh });
  const cancel = useMutation({ mutationFn: leaveApi.cancel, onSuccess: refresh });
  const openForm = () => { setError(""); setForm({ fromDate: "", toDate: "", reason: "" }); setOpen(true); };

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Time away</p><h1 className="mt-1 text-3xl font-extrabold">{admin ? "Leave management" : "My leave"}</h1><p className="mt-2 text-sm text-slate-500">{admin ? "Review staff leave requests and record decisions." : "Apply for leave and track approval status."}</p></div>{!admin && <button onClick={openForm} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white"><Plus className="mr-2 inline h-4 w-4" />Apply for leave</button>}</div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border-l-4 border-orange-500 bg-white p-5 shadow-sm"><Clock3 className="h-5 w-5 text-orange-500" /><p className="mt-4 text-3xl font-extrabold">{summary.pending || 0}</p><p className="text-xs font-bold uppercase text-slate-400">Pending</p></div><div className="rounded-2xl border-l-4 border-emerald-500 bg-white p-5 shadow-sm"><Check className="h-5 w-5 text-emerald-500" /><p className="mt-4 text-3xl font-extrabold">{summary.approved || 0}</p><p className="text-xs font-bold uppercase text-slate-400">Approved</p></div><div className="rounded-2xl border-l-4 border-red-500 bg-white p-5 shadow-sm"><X className="h-5 w-5 text-red-500" /><p className="mt-4 text-3xl font-extrabold">{summary.rejected || 0}</p><p className="text-xs font-bold uppercase text-slate-400">Rejected</p></div></div>
    {admin && <div className="mt-5 flex justify-end"><select value={filter} onChange={e => setFilter(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm"><option value="">All requests</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div>}
    <div className="mt-5 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400">{admin && <th className="p-5">Staff member</th>}<th className="p-5">Dates</th><th className="p-5">Duration</th><th className="p-5">Reason</th><th className="p-5">Status</th><th className="p-5 text-right">Actions</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={6} className="p-12 text-center text-slate-400">Loading…</td></tr> : requests.length === 0 ? <tr><td colSpan={6} className="p-12 text-center text-slate-400">No leave requests found.</td></tr> : requests.map((request: any) => <tr key={request.id} className="border-b last:border-0">{admin && <td className="p-5"><p className="font-bold">{request.user.name}</p><p className="text-xs capitalize text-slate-400">{request.user.role}</p></td>}<td className="p-5"><p className="font-semibold">{date(request.fromDate)} – {date(request.toDate)}</p></td><td className="p-5">{days(request.fromDate, request.toDate)} day{days(request.fromDate, request.toDate) === 1 ? "" : "s"}</td><td className="max-w-xs p-5 text-slate-600">{request.reason}</td><td className="p-5"><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${statusClass[request.status]}`}>{request.status}</span></td><td className="p-5"><div className="flex justify-end gap-2">{admin && request.status === "pending" && <><button onClick={() => decide.mutate({ id: request.id, status: "approved" })} className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><Check className="mr-1 inline h-3.5 w-3.5" />Approve</button><button onClick={() => decide.mutate({ id: request.id, status: "rejected" })} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700"><X className="mr-1 inline h-3.5 w-3.5" />Reject</button></>}{!admin && request.status === "pending" && <button onClick={() => confirm("Cancel this leave request?") && cancel.mutate(request.id)} className="rounded-lg border border-red-100 p-2 text-red-500" title="Cancel request"><Trash2 className="h-4 w-4" /></button>}</div></td></tr>)}</tbody></table></div></div>
    {open && <Modal title="Apply for leave" onClose={() => setOpen(false)}><form onSubmit={(e: FormEvent) => { e.preventDefault(); create.mutate(); }} className="space-y-5 p-6">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">From date<input type="date" value={form.fromDate} onChange={e => setForm({ ...form, fromDate: e.target.value, ...(form.toDate && form.toDate < e.target.value ? { toDate: e.target.value } : {}) })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><label className="text-sm font-semibold">To date<input type="date" min={form.fromDate} value={form.toDate} onChange={e => setForm({ ...form, toDate: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label></div><label className="block text-sm font-semibold">Reason<textarea value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} rows={4} required placeholder="Explain why you need leave" className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label>{form.fromDate && form.toDate && <p className="rounded-xl bg-blue-50 p-3 text-sm text-blue-700"><CalendarDays className="mr-2 inline h-4 w-4" />Requested duration: <b>{days(form.fromDate, form.toDate)} day(s)</b></p>}<button disabled={create.isPending} className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-60">{create.isPending ? "Submitting…" : "Submit leave request"}</button></form></Modal>}
  </div>;
}
