import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowDown, ArrowUp, Boxes, Pencil, Plus, Trash2, Truck } from "lucide-react";
import { inventoryApi } from "../../api/inventoryApi";
import Modal from "../../components/common/Modal";
import { useAuth } from "../../context/AuthContext";

const money = (value: unknown) => `₹${Number(value).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

export default function Inventory() {
  const { user } = useAuth(); const admin = user?.role === "admin"; const client = useQueryClient();
  const [itemModal, setItemModal] = useState<any>(null); const [supplierModal, setSupplierModal] = useState<any>(null); const [transactionOpen, setTransactionOpen] = useState(false); const [error, setError] = useState("");
  const [itemForm, setItemForm] = useState<Record<string, string>>({}); const [supplierForm, setSupplierForm] = useState<Record<string, string>>({}); const [transactionForm, setTransactionForm] = useState<Record<string, string>>({ type: "in", date: new Date().toISOString().slice(0, 10) });
  const { data: items = [], isLoading } = useQuery({ queryKey: ["inventory"], queryFn: inventoryApi.items });
  const { data: suppliers = [] } = useQuery({ queryKey: ["suppliers"], queryFn: inventoryApi.suppliers, enabled: admin });
  const { data: transactions = [] } = useQuery({ queryKey: ["stock-transactions"], queryFn: inventoryApi.transactions, enabled: admin });
  const refresh = () => { client.invalidateQueries({ queryKey: ["inventory"] }); client.invalidateQueries({ queryKey: ["stock-transactions"] }); };
  const saveItem = useMutation({ mutationFn: () => itemModal?.id ? inventoryApi.updateItem(itemModal.id, itemForm) : inventoryApi.createItem(itemForm), onSuccess: () => { refresh(); setItemModal(null); }, onError: (e: any) => setError(e.response?.data?.message || "Could not save item.") });
  const deleteItem = useMutation({ mutationFn: inventoryApi.deleteItem, onSuccess: refresh });
  const saveSupplier = useMutation({ mutationFn: () => supplierModal?.id ? inventoryApi.updateSupplier(supplierModal.id, supplierForm) : inventoryApi.createSupplier(supplierForm), onSuccess: () => { client.invalidateQueries({ queryKey: ["suppliers"] }); setSupplierModal(null); }, onError: (e: any) => setError(e.response?.data?.message || "Could not save supplier.") });
  const deleteSupplier = useMutation({ mutationFn: inventoryApi.deleteSupplier, onSuccess: () => client.invalidateQueries({ queryKey: ["suppliers"] }) });
  const addTransaction = useMutation({ mutationFn: () => inventoryApi.createTransaction(transactionForm), onSuccess: () => { refresh(); setTransactionOpen(false); }, onError: (e: any) => setError(e.response?.data?.message || "Could not update stock.") });
  const openItem = (item?: any) => { setError(""); setItemModal(item || {}); setItemForm(item ? { itemName: item.itemName, unit: item.unit, reorderLevel: String(item.reorderLevel), pricePerUnit: String(item.pricePerUnit) } : { itemName: "", unit: "pieces", quantity: "0", reorderLevel: "0", pricePerUnit: "0" }); };
  const openSupplier = (supplier?: any) => { setError(""); setSupplierModal(supplier || {}); setSupplierForm(supplier ? { name: supplier.name, contact: supplier.contact, itemSupplied: supplier.itemSupplied } : { name: "", contact: "", itemSupplied: "" }); };
  const openTransaction = () => { setError(""); setTransactionForm({ inventoryId: "", supplierId: "", type: "in", quantity: "", date: new Date().toISOString().slice(0, 10) }); setTransactionOpen(true); };
  const lowStock = items.filter((item: any) => Number(item.quantity) <= Number(item.reorderLevel));
  const stockValue = items.reduce((sum: number, item: any) => sum + Number(item.quantity) * Number(item.pricePerUnit), 0);

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Stock control</p><h1 className="mt-1 text-3xl font-extrabold">Inventory</h1><p className="mt-2 text-sm text-slate-500">Monitor supplies, reorder levels, and stock movement.</p></div>{admin && <div className="flex flex-wrap gap-2"><button onClick={() => openSupplier()} className="rounded-xl border border-blue-200 px-4 py-3 text-sm font-bold text-blue-700"><Truck className="mr-1 inline h-4 w-4" />Supplier</button><button onClick={openTransaction} className="rounded-xl border border-emerald-200 px-4 py-3 text-sm font-bold text-emerald-700"><Boxes className="mr-1 inline h-4 w-4" />Stock movement</button><button onClick={() => openItem()} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white"><Plus className="mr-1 inline h-4 w-4" />Item</button></div>}</div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border-l-4 border-blue-500 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">Inventory items</p><p className="mt-2 text-3xl font-extrabold">{items.length}</p></div><div className="rounded-2xl border-l-4 border-emerald-500 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">Stock value</p><p className="mt-2 text-3xl font-extrabold">{money(stockValue)}</p></div><div className="rounded-2xl border-l-4 border-orange-500 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase text-slate-400">Low stock</p><p className="mt-2 text-3xl font-extrabold text-orange-600">{lowStock.length}</p></div></div>
    <div className="mt-6 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="p-5">Item</th><th className="p-5">Available</th><th className="p-5">Reorder at</th><th className="p-5">Unit price</th><th className="p-5">Status</th>{admin && <th className="p-5 text-right">Actions</th>}</tr></thead><tbody>{isLoading ? <tr><td colSpan={6} className="p-12 text-center text-slate-400">Loading…</td></tr> : items.length === 0 ? <tr><td colSpan={6} className="p-12 text-center text-slate-400">No inventory items yet.</td></tr> : items.map((item: any) => { const low = Number(item.quantity) <= Number(item.reorderLevel); return <tr key={item.id} className="border-b last:border-0"><td className="p-5 font-bold">{item.itemName}</td><td className="p-5"><b>{Number(item.quantity)}</b> {item.unit}</td><td className="p-5 text-slate-500">{Number(item.reorderLevel)} {item.unit}</td><td className="p-5">{money(item.pricePerUnit)}</td><td className="p-5"><span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-bold ${low ? "bg-orange-50 text-orange-700" : "bg-emerald-50 text-emerald-700"}`}>{low && <AlertTriangle className="h-3 w-3" />}{low ? "Reorder" : "In stock"}</span></td>{admin && <td className="p-5"><div className="flex justify-end gap-2"><button onClick={() => openItem(item)} className="p-2 text-slate-500"><Pencil className="h-4 w-4" /></button><button onClick={() => confirm("Delete this item and its stock history?") && deleteItem.mutate(item.id)} className="p-2 text-red-500"><Trash2 className="h-4 w-4" /></button></div></td>}</tr>; })}</tbody></table></div></div>
    {admin && <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-extrabold">Suppliers</h2><span className="text-xs text-slate-400">{suppliers.length} total</span></div><div className="mt-3 divide-y">{suppliers.length === 0 ? <p className="py-8 text-center text-sm text-slate-400">No suppliers added.</p> : suppliers.map((supplier: any) => <div key={supplier.id} className="flex items-center gap-3 py-3"><div className="flex-1"><p className="font-semibold">{supplier.name}</p><p className="text-xs text-slate-400">{supplier.contact} · {supplier.itemSupplied}</p></div><button onClick={() => openSupplier(supplier)} className="p-2 text-slate-500"><Pencil className="h-4 w-4" /></button><button onClick={() => confirm("Delete this supplier?") && deleteSupplier.mutate(supplier.id)} className="p-2 text-red-500"><Trash2 className="h-4 w-4" /></button></div>)}</div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-extrabold">Recent stock movement</h2><div className="mt-3 divide-y">{transactions.slice(0, 8).map((entry: any) => <div key={entry.id} className="flex items-center gap-3 py-3"><span className={`grid h-8 w-8 place-items-center rounded-lg ${entry.type === "in" ? "bg-emerald-50 text-emerald-600" : "bg-red-50 text-red-600"}`}>{entry.type === "in" ? <ArrowDown className="h-4 w-4" /> : <ArrowUp className="h-4 w-4" />}</span><div className="flex-1"><p className="text-sm font-semibold">{entry.inventory.itemName}</p><p className="text-xs text-slate-400">{new Date(entry.date).toLocaleString("en-IN")} {entry.supplier && `· ${entry.supplier.name}`}</p></div><b className={entry.type === "in" ? "text-emerald-600" : "text-red-600"}>{entry.type === "in" ? "+" : "−"}{Number(entry.quantity)} {entry.inventory.unit}</b></div>)}</div></section></div>}
    {itemModal && <Modal title={itemModal.id ? "Edit inventory item" : "Add inventory item"} onClose={() => setItemModal(null)}><form onSubmit={(e: FormEvent) => { e.preventDefault(); saveItem.mutate(); }} className="grid gap-5 p-6 sm:grid-cols-2">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p>}<label className="text-sm font-semibold sm:col-span-2">Item name<input value={itemForm.itemName || ""} onChange={e => setItemForm({ ...itemForm, itemName: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><label className="text-sm font-semibold">Unit<input value={itemForm.unit || ""} onChange={e => setItemForm({ ...itemForm, unit: e.target.value })} required placeholder="pieces, reams, bottles" className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label>{!itemModal.id && <label className="text-sm font-semibold">Opening quantity<input type="number" min="0" step="0.01" value={itemForm.quantity || ""} onChange={e => setItemForm({ ...itemForm, quantity: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label>}<label className="text-sm font-semibold">Reorder level<input type="number" min="0" step="0.01" value={itemForm.reorderLevel || ""} onChange={e => setItemForm({ ...itemForm, reorderLevel: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><label className="text-sm font-semibold">Price per unit<input type="number" min="0" step="0.01" value={itemForm.pricePerUnit || ""} onChange={e => setItemForm({ ...itemForm, pricePerUnit: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><button className="rounded-xl bg-blue-600 py-3 font-bold text-white sm:col-span-2">Save item</button></form></Modal>}
    {supplierModal && <Modal title={supplierModal.id ? "Edit supplier" : "Add supplier"} onClose={() => setSupplierModal(null)}><form onSubmit={(e: FormEvent) => { e.preventDefault(); saveSupplier.mutate(); }} className="space-y-5 p-6">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{[["name", "Supplier name"], ["contact", "Contact number"], ["itemSupplied", "Item supplied"]].map(([key, label]) => <label key={key} className="block text-sm font-semibold">{label}<input value={supplierForm[key] || ""} onChange={e => setSupplierForm({ ...supplierForm, [key]: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label>)}<button className="w-full rounded-xl bg-blue-600 py-3 font-bold text-white">Save supplier</button></form></Modal>}
    {transactionOpen && <Modal title="Record stock movement" onClose={() => setTransactionOpen(false)}><form onSubmit={(e: FormEvent) => { e.preventDefault(); addTransaction.mutate(); }} className="space-y-5 p-6">{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="block text-sm font-semibold">Inventory item<select value={transactionForm.inventoryId || ""} onChange={e => setTransactionForm({ ...transactionForm, inventoryId: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"><option value="">Select item</option>{items.map((item: any) => <option key={item.id} value={item.id}>{item.itemName} · {Number(item.quantity)} {item.unit}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Movement<select value={transactionForm.type} onChange={e => setTransactionForm({ ...transactionForm, type: e.target.value, supplierId: e.target.value === "out" ? "" : transactionForm.supplierId })} className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"><option value="in">Stock in</option><option value="out">Stock out</option></select></label><label className="text-sm font-semibold">Quantity<input type="number" min="0.01" step="0.01" value={transactionForm.quantity || ""} onChange={e => setTransactionForm({ ...transactionForm, quantity: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label></div>{transactionForm.type === "in" && <label className="block text-sm font-semibold">Supplier<select value={transactionForm.supplierId || ""} onChange={e => setTransactionForm({ ...transactionForm, supplierId: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal"><option value="">Select supplier</option>{suppliers.map((supplier: any) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label>}<label className="block text-sm font-semibold">Date<input type="date" value={transactionForm.date} onChange={e => setTransactionForm({ ...transactionForm, date: e.target.value })} required className="mt-2 w-full rounded-xl border px-3 py-3 font-normal" /></label><button className="w-full rounded-xl bg-emerald-600 py-3 font-bold text-white">Update stock</button></form></Modal>}
  </div>;
}
