import { useState } from "react";
import { Award, Banknote, BarChart3, Bell, BookOpen, Boxes, CalendarCheck, CalendarOff, ChevronDown, CircleDollarSign, ClipboardList, Files, GraduationCap, LayoutDashboard, LogOut, Menu, ReceiptText, Search, Sparkles, TrendingDown, UserCheck, Users, X } from "lucide-react";
import { NavLink, Outlet } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

const links = [
  ["Dashboard", "/admin/dashboard", LayoutDashboard], ["Approvals", "/admin/approvals", UserCheck],
  ["Students", "/admin/students", GraduationCap], ["Teachers", "/admin/teachers", Users],
  ["Employees", "/admin/employees", Users], ["Courses", "/admin/courses", BookOpen], ["Batches", "/admin/batches", Boxes], ["Attendance", "/admin/attendance", CalendarCheck], ["Fees", "/admin/fees", Banknote], ["Salary", "/admin/salary", CircleDollarSign], ["Materials", "/admin/materials", Files], ["Assignments", "/admin/assignments", ClipboardList], ["Results", "/admin/results", Award], ["Billing", "/admin/billing", ReceiptText], ["Inventory", "/admin/inventory", Boxes], ["Expenses", "/admin/expenses", TrendingDown], ["Reports", "/admin/reports", BarChart3], ["Leave", "/admin/leave", CalendarOff]
] as const;

export default function AdminLayout() {
  const [open, setOpen] = useState(false); const { user, logout } = useAuth();
  return <div className="min-h-screen bg-slate-50"><aside className={`fixed inset-y-0 left-0 z-40 flex h-screen w-64 flex-col bg-[#0B1120] p-5 text-white transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="shrink-0 flex items-center justify-between"><span className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-blue-500 to-emerald-400"><Sparkles className="h-4 w-4" /></span><b className="text-xl">Ailyt</b></span><button onClick={() => setOpen(false)} className="lg:hidden"><X /></button></div><p className="mb-3 mt-8 shrink-0 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-slate-600">Workspace</p><nav className="min-h-0 flex-1 space-y-1 overflow-y-auto overscroll-contain pr-1">{links.map(([label, href, Icon]) => <NavLink key={href} to={href} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive ? "bg-blue-600 text-white" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4.5 w-4.5 shrink-0" />{label}</NavLink>)}</nav><div className="shrink-0 border-t border-white/10 bg-[#0B1120] pt-4"><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl border border-white/10 px-3 py-2.5 text-sm text-slate-400 hover:bg-white/5 hover:text-white"><LogOut className="h-4 w-4" />Sign out</button></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center gap-4 border-b border-slate-200 bg-white/90 px-5 backdrop-blur lg:px-8"><button onClick={() => setOpen(true)} className="rounded-lg border border-slate-200 p-2 lg:hidden"><Menu /></button><div className="relative hidden max-w-md flex-1 sm:block"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input placeholder="Search students, phone, email..." className="w-full rounded-xl bg-slate-100 py-2.5 pl-10 pr-4 text-sm outline-none focus:ring-2 focus:ring-blue-100" /></div><div className="ml-auto flex items-center gap-4"><button className="relative rounded-xl border border-slate-200 p-2.5 text-slate-500"><Bell className="h-4.5 w-4.5" /></button><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 font-bold text-blue-700">{user?.name?.[0]}</span><div className="hidden sm:block"><p className="text-sm font-bold text-slate-900">{user?.name}</p><p className="text-xs capitalize text-slate-500">{user?.role}</p></div><ChevronDown className="hidden h-4 w-4 text-slate-400 sm:block" /></div></div></header><main className="p-5 lg:p-8"><Outlet /></main></div></div>;
}
