import { Award, Banknote, BarChart3, Boxes, CalendarCheck, CalendarOff, CircleDollarSign, ClipboardList, Files, LayoutDashboard, LogOut, Menu, ReceiptText, Sparkles, UserRound, Users, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState } from "react";
import { NavLink, Outlet } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

export default function PortalLayout() {
  const [open, setOpen] = useState(false); const { user, logout } = useAuth(); const base = `/${user?.role}`;
  const links: Array<[string, string, LucideIcon]> = [["Dashboard", `${base}/dashboard`, LayoutDashboard], ...(user?.role === "teacher" ? [["Batch attendance", `${base}/attendance`, Users], ["Reports", `${base}/reports`, BarChart3]] as Array<[string, string, LucideIcon]> : []), ["My attendance", `${base}/my-attendance`, CalendarCheck], ...(user?.role === "student" ? [["My fees", `${base}/fees`, Banknote] as [string, string, LucideIcon]] : [["My salary", `${base}/salary`, CircleDollarSign] as [string, string, LucideIcon]]), ...(["teacher", "employee"].includes(user?.role || "") ? [["My leave", `${base}/leave`, CalendarOff]] as Array<[string, string, LucideIcon]> : []), ...(user?.role === "employee" ? [["Billing", `${base}/billing`, ReceiptText], ["Inventory", `${base}/inventory`, Boxes]] as Array<[string, string, LucideIcon]> : []), ...(["teacher", "student"].includes(user?.role || "") ? [["Materials", `${base}/materials`, Files], ["Assignments", `${base}/assignments`, ClipboardList], ["Results", `${base}/results`, Award]] as Array<[string, string, LucideIcon]> : [])];
  return <div className="min-h-screen bg-slate-50"><aside className={`fixed inset-y-0 left-0 z-40 flex h-screen w-64 flex-col bg-[#0B1120] p-5 text-white transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="shrink-0 flex items-center justify-between"><span className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-blue-500 to-emerald-400"><Sparkles className="h-4 w-4" /></span><b className="text-xl">Ailyt</b></span><button onClick={() => setOpen(false)} className="lg:hidden"><X /></button></div><p className="mb-3 mt-8 shrink-0 px-3 text-[10px] font-bold uppercase tracking-[.18em] text-slate-600">{user?.role} portal</p><nav className="min-h-0 flex-1 space-y-1 overflow-y-auto overscroll-contain pr-1">{links.map(([label, href, Icon]) => <NavLink key={href} to={href} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${isActive ? "bg-blue-600 text-white" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4 w-4 shrink-0" />{label}</NavLink>)}</nav><div className="shrink-0 border-t border-white/10 bg-[#0B1120] pt-4"><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl border border-white/10 px-3 py-2.5 text-sm text-slate-400 hover:bg-white/5 hover:text-white"><LogOut className="h-4 w-4" />Sign out</button></div></aside><div className="lg:pl-64"><header className="flex h-20 items-center border-b border-slate-200 bg-white px-5 lg:px-8"><button onClick={() => setOpen(true)} className="rounded-lg border p-2 lg:hidden"><Menu /></button><div className="ml-auto flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-100 font-bold text-blue-700"><UserRound className="h-5 w-5" /></span><div><p className="text-sm font-bold">{user?.name}</p><p className="text-xs capitalize text-slate-500">{user?.role}</p></div></div></header><main className="p-5 lg:p-8"><Outlet /></main></div></div>;
}
