import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clock3, X } from "lucide-react";
import { adminApi } from "../../api/adminApi";

export default function Approvals() {
  const client = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ["admin", "approvals"], queryFn: () => adminApi.list("approvals") });
  const decide = useMutation({ mutationFn: ({ id, status }: { id: number; status: "active" | "rejected" }) => adminApi.decide(id, status), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin", "approvals"] }); client.invalidateQueries({ queryKey: ["admin-dashboard"] }); } });
  const rows = data?.data || [];
  return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-600">Account review</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">Pending approvals</h1><p className="mt-2 text-sm text-slate-500">Review teacher registrations before granting dashboard access.</p><div className="mt-7 overflow-hidden rounded-2xl bg-white shadow-sm">{isLoading ? <p className="p-10 text-center text-slate-400">Loading…</p> : rows.length === 0 ? <div className="p-12 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-50"><Check className="text-emerald-600" /></span><h2 className="mt-4 font-bold text-slate-900">All caught up</h2><p className="mt-1 text-sm text-slate-500">There are no teacher accounts waiting for review.</p></div> : rows.map((row: any) => <div key={row.id} className="flex flex-col gap-5 border-b border-slate-100 p-5 last:border-0 sm:flex-row sm:items-center"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-orange-50 font-bold text-orange-700">{row.name[0]}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-bold text-slate-900">{row.name}</p><span className="inline-flex items-center gap-1 rounded-full bg-orange-50 px-2 py-1 text-[10px] font-bold uppercase text-orange-700"><Clock3 className="h-3 w-3" />Pending</span></div><p className="mt-1 text-sm text-slate-500">{row.email} · {row.phone}</p><p className="mt-2 text-xs text-slate-500"><b>Expertise:</b> {row.teacher?.expertise} · <b>Qualification:</b> {row.teacher?.qualification}</p></div><div className="flex gap-2"><button onClick={() => decide.mutate({ id: row.id, status: "rejected" })} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-600 hover:bg-red-50"><X className="h-4 w-4" />Reject</button><button onClick={() => decide.mutate({ id: row.id, status: "active" })} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-500"><Check className="h-4 w-4" />Approve</button></div></div>)}</div></div>;
}
