import { useQuery } from "@tanstack/react-query";
import { BookOpen, Boxes, GraduationCap, UserCheck, Users } from "lucide-react";
import { adminApi } from "../../api/adminApi";

export default function Dashboard() {
  const { data = {}, isLoading } = useQuery({ queryKey: ["admin-dashboard"], queryFn: adminApi.dashboard });
  const cards = [["Students", data.students, GraduationCap, "border-blue-500", "text-blue-500"], ["Teachers", data.teachers, Users, "border-emerald-500", "text-emerald-500"], ["Pending approvals", data.pendingTeachers, UserCheck, "border-orange-500", "text-orange-500"], ["Active batches", data.batches, Boxes, "border-violet-500", "text-violet-500"]] as const;
  return <div><p className="text-sm font-semibold text-blue-600">ADMIN OVERVIEW</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">Good day, Admin</h1><p className="mt-2 text-sm text-slate-500">Here’s what’s happening across Ailyt today.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, border, iconColor]) => <div key={label} className={`rounded-2xl border-l-4 ${border} bg-white p-5 shadow-sm`}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-3 text-3xl font-extrabold text-slate-950">{isLoading ? "—" : value ?? 0}</p><p className="mt-2 text-xs text-slate-400">Current total</p></div><Icon className={`h-5 w-5 ${iconColor}`} /></div></div>)}</div><div className="mt-7 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-950">Recent activity</h2><div className="mt-5 rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">Activity will appear as your team uses Ailyt.</div></div><div className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-950">Quick overview</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-blue-50 p-4"><BookOpen className="h-5 w-5 text-blue-600" /><p className="mt-3 text-2xl font-bold">{data.courses ?? 0}</p><p className="text-xs text-slate-500">Courses</p></div><div className="rounded-xl bg-violet-50 p-4"><Boxes className="h-5 w-5 text-violet-600" /><p className="mt-3 text-2xl font-bold">{data.batches ?? 0}</p><p className="text-xs text-slate-500">Batches</p></div></div></div></div></div>;
}
